export const typography = {
  fontFamily: {
    body: 'PlusJakartaSans_400Regular',
    bodyMedium: 'PlusJakartaSans_500Medium',
    bodySemiBold: 'PlusJakartaSans_600SemiBold',
    bodyBold: 'PlusJakartaSans_700Bold',
    display: 'PlusJakartaSans_700Bold',
  },
  size: {
    xs: 12,
    sm: 14,
    base: 16,
    lg: 18,
    xl: 20,
    '2xl': 24,
    '3xl': 30,
    // backward compat aliases
    legal: 12,
    caption: 13,
    body: 14,
    labelMd: 15,
    button: 15,
    titleSm: 16,
    titleMd: 18,
    titleLg: 20,
    displayMd: 24,
    displayLg: 28,
    displayXl: 32,
  },
  lineHeight: {
    tight: 1.25,
    normal: 1.5,
    relaxed: 1.6,
  },
} as const;
